kind = "web"
previewPath = "/"
title = "TRANSLTR"
version = "1.0.0"
id = "artifacts/transltr"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20146

[services.development]
run = "pnpm --filter @workspace/transltr run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/transltr", "run", "build" ]
publicDir = "artifacts/transltr/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20146"
BASE_PATH = "/"
